version: "2"

run:
  timeout: 5m

issues:
  fix: true
  exclude-rules:
    # Disable complexity checks for debug package (contains necessary reflection code)
    - path: debug/
      linters:
        - cyclop
        - gocognit
        - nestif

linters:
  enable:
    # Essential Go linters (enabled by default)
    - govet           # Official Go static analyzer
    - ineffassign     # Detects ineffectual assignments
    - errcheck        # Check for unchecked errors
    - staticcheck     # Advanced static analysis
    - unused          # Find unused code

    # Security and correctness
    - gosec           # Security analysis
    - bodyclose       # Check HTTP response body closure
    - rowserrcheck    # Check sql.Rows.Err
    - sqlclosecheck   # Check SQL resource closure

    # Code quality and style
    - misspell        # Fix spelling mistakes
    - revive          # Go style guide enforcement
    - gocritic        # Comprehensive diagnostics

    # Complexity and maintainability
    - gocyclo         # Cyclomatic complexity
    - funlen          # Function length
    - lll             # Line length
    - gocognit        # Cognitive complexity
    - nestif          # Nested if statements
    - cyclop          # Alternative complexity checker

    # Performance and best practices
    - prealloc        # Suggest slice preallocation
    - unconvert       # Remove unnecessary conversions
    - wastedassign    # Find wasted assignments
    - whitespace      # Whitespace issues
    - goconst         # Find repeated strings for constants
    - unparam         # Find unused function parameters

  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disable-stuttering-check
    cyclop:
      max-complexity: 10
      skip-tests: true
    gocognit:
      min-complexity: 30
