# markdownlint-cli2 configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Always fix issues
fix: true

# Always use human-readable forms of rules instead of the `MD0123` format.
config:
  line-length:
    line_length: 100
    # Allow long lines in code blocks and tables
    code_blocks: false
    tables: false
    headings: false

# Ignore files with .ignored.md extension
ignores:
- "*.ignored.md"
