repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/TekWizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-fumpt
    args: [-w]
  - id: go-vet-mod
  - id: golangci-lint-mod

- repo: https://github.com/segmentio/golines
  rev: v0.12.2
  hooks:
  - id: golines
    args: [--max-len=100, --base-formatter=goimports]

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.18.1
  hooks:
  - id: markdownlint-cli2
